#!/bin/bash

setterm -foreground cyan
cat arg.txt
amarillo="\033[1;33m"
blanco="\033[1;37m"
rojo="\033[1;31m"
cyan="\033[1;36m"

echo -e "$rojo---------------------------------"
echo -e "\e[1;37m[\e[0m\e[1;31m#\e[0m\e[1;37m]\e[0m \e[1;33mEscribe la CC a extrapolar\e[0m " 
read -p "CC: " Extrapolacion
echo -e "$rojo---------------------------------"
echo -e "$amarillo"
echo -e "\e[1;34m==\e[0m\e[1;37m==\e[0m\e[1;34m==\e[0m\e[1;32mBIN RAPPI EXTRAPOLADOS\e[0m\e[1;34m==\e[0m\e[1;37m==\e[0m\e[1;34m==\e[0m"
echo ""
setterm -foreground blue
echo "[☆]Cargando nuevos bin de rappi ..."
sleep 2
echo ""
echo -e "\e[1;36mBIN\e[0m $blanco${Extrapolacion:0:12}xxxx "
echo -e "\e[1;36mBIN\e[0m $blanco${Extrapolacion:0:11}xxxxx "
echo -e "\e[1;36mBIN\e[0m $blanco${Extrapolacion:0:8}xxxx${Extrapolacion:12:1}x${Extrapolacion:14:16} "
echo -e "\e[1;36mBIN\e[0m $blanco${Extrapolacion:0:10}xxxxxx "
echo -e "\e[1;36mBIN\e[0m $blanco${Extrapolacion:0:6}x${Extrapolacion:7:1}x${Extrapolacion:9:1}x${Extrapolacion:11:1}x${Extrapolacion:13:1}x${Extrapolacion:15:1} "



